### ISSUE TITLE
Problem connecting to MongoDB

### ISSUE THREAD

**Issue by Chakerbh** [linagora/openpaas-esn#13]
Hey,

I'm Trying to start Openpass-esn with docker. I followed the [README](https://github.com/linagora/openpaas-esn/tree/master/docker/dockerfiles/platform) file. All went well while building. However when I try to run the container I get this error over and over again

```

➜  openpaas-esn git:(master) PROVISION=true DOCKER_IP=localhost ESN_PATH=$PWD docker-compose -f ./docker/dockerfiles/platform/docker-compose-images.yml up
...
...
...
...
mongo_1          | 2016-06-29T10:29:42.969+0000 [conn103] end connection 172.18.0.9:35306 (9 connections now open)
mongo_1          | 2016-06-29T10:29:42.969+0000 [conn102] end connection 172.18.0.9:35304 (9 connections now open)
mongo_1          | 2016-06-29T10:29:42.970+0000 [conn104] end connection 172.18.0.9:35308 (7 connections now open)
mongo_1          | 2016-06-29T10:29:42.970+0000 [conn105] end connection 172.18.0.9:35310 (6 connections now open)
mongo_1          | 2016-06-29T10:29:42.970+0000 [conn106] end connection 172.18.0.9:35312 (6 connections now open)
mongo_1          | 2016-06-29T10:29:42.971+0000 [conn109] end connection 172.18.0.9:35318 (4 connections now open)
mongo_1          | 2016-06-29T10:29:42.971+0000 [conn110] end connection 172.18.0.9:35320 (3 connections now open)
mongo_1          | 2016-06-29T10:29:42.972+0000 [conn111] end connection 172.18.0.9:35322 (2 connections now open)
mongo_1          | 2016-06-29T10:29:42.972+0000 [conn108] end connection 172.18.0.9:35316 (1 connection now open)
mongo_1          | 2016-06-29T10:29:42.973+0000 [conn107] end connection 172.18.0.9:35314 (0 connections now open)
mongo_1          | 2016-06-29T10:29:43.971+0000 [initandlisten] connection accepted from 172.18.0.9:35348 #112 (1 connection now open)
mongo_1          | 2016-06-29T10:29:43.974+0000 [initandlisten] connection accepted from 172.18.0.9:35350 #113 (2 connections now open)
mongo_1          | 2016-06-29T10:29:43.976+0000 [initandlisten] connection accepted from 172.18.0.9:35352 #114 (3 connections now open)
mongo_1          | 2016-06-29T10:29:43.977+0000 [initandlisten] connection accepted from 172.18.0.9:35354 #115 (4 connections now open)
mongo_1          | 2016-06-29T10:29:43.979+0000 [initandlisten] connection accepted from 172.18.0.9:35356 #116 (5 connections now open)
mongo_1          | 2016-06-29T10:29:43.980+0000 [initandlisten] connection accepted from 172.18.0.9:35358 #117 (6 connections now open)
mongo_1          | 2016-06-29T10:29:43.981+0000 [initandlisten] connection accepted from 172.18.0.9:35360 #118 (7 connections now open)
mongo_1          | 2016-06-29T10:29:43.982+0000 [initandlisten] connection accepted from 172.18.0.9:35362 #119 (8 connections now open)
mongo_1          | 2016-06-29T10:29:43.984+0000 [initandlisten] connection accepted from 172.18.0.9:35364 #120 (9 connections now open)
mongo_1          | 2016-06-29T10:29:43.985+0000 [initandlisten] connection accepted from 172.18.0.9:35366 #121 (10 connections now open)
esn              | error: Failed to connect to MongoDB: Error: connection to [mongo:27017] timed out
esn              |     at Db.<anonymous> (/var/www/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:154:17)
esn              |     at Db.emit (events.js:98:17)
esn              |     at emit (/var/www/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:255:19)
esn              |     at Server.Base._emitAcrossAllDbInstances (/var/www/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:512:17)
esn              |     at null.<anonymous> (/var/www/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:530:14)
esn              |     at emit (events.js:95:17)
esn              |     at null.<anonymous> (/var/www/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:178:15)
esn              |     at emit (events.js:98:17)
esn              |     at Socket.<anonymous> (/var/www/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:519:10)
esn              |     at Socket.emit (events.js:92:17)
esn              |     at Socket._onTimeout (net.js:327:8)
esn              |     at _makeTimerTimeout (timers.js:429:11)
esn              |     at Timer.unrefTimeout [as ontimeout] (timers.js:493:5)

```

System information: 

```
➜  ~ uname -rms
Linux 4.6.2-1-ARCH x86_64

➜  ~ docker --version
Docker version 1.11.2, build b9f10c9

➜  ~ docker-compose --version 
docker-compose version 1.7.1, build 0a9ab35

```

Thanks!

**Comment by thomas-hilaire** [comment]
Hello @Chakerbh,

I didn't have investigated about why this error appears, but your platform should work properly even with this log. What happen if you open your browser on [http://localhost:8080](http://localhost:8080) and try to login with "user0@open-paas.org" and "secret" as password ?

Thanks for your report anyway!

**Comment by Chakerbh** [comment]
Thanks @thomas-hilaire 
It works well now! even though this doesn't seem to be a problem, I suggest to live the issue open until someone investigate about it.
thanks again.
