### ISSUE TITLE
Docker install : Error: [invalid_alias_name_exception] Invalid alias name [users.idx]

### ISSUE THREAD

**Issue by GuillaumeDesforges** [linagora/openpaas-esn#31]
Pour installer avec Docker :

```
~/projects/openpaas-esn $ node ./bin/cli elasticsearch --host localhost --port 9200 --index usersdebug: local/SUBSCRIBE to mongodb:connectionAvailable
[CLI] ERROR { Error: [invalid_alias_name_exception] Invalid alias name [users.idx], an index exists with the same name as the alias, with { index=real.users.idx }
    at respond (/home/arsleust/projects/openpaas-esn/node_modules/elasticsearch/src/lib/transport.js:289:15)
    at checkRespForFailure (/home/arsleust/projects/openpaas-esn/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/home/arsleust/projects/openpaas-esn/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/home/arsleust/projects/openpaas-esn/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  status: 400,
  displayName: 'BadRequest',
  message: '[invalid_alias_name_exception] Invalid alias name [users.idx], an index exists with the same name as the alias, with { index=real.users.idx }',
  path: '/real.users.idx/_alias/users.idx',
  query: {},
  body: undefined,
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"invalid_alias_name_exception","reason":"Invalid alias name [users.idx], an index exists with the same name as the alias","index":"real.users.idx"}],"type":"invalid_alias_name_exception","reason":"Invalid alias name [users.idx], an index exists with the same name as the alias","index":"real.users.idx"},"status":400}',
  toString: [Function],
  toJSON: [Function] }
```

**Comment by tuanlc** [comment]
Hello @GuillaumeDesforges 

Thank you for your feedback.

The document about CLI for elasticsearch is out date.
In your case, it should be:

```bash
node ./bin/cli elasticsearch --host localhost --port 9200 --type users
```

Sorry about this. We will update the document as soon as possible.

**Comment by GuillaumeDesforges** [comment]
Hello @tuanlc 
Thank you for your quick answer

I still can't manage to make it work (dev purpose). I have the docker-compose services upped, yet in the doc, following instructions given here https://github.com/linagora/openpaas-esn/blob/master/docker/doc/install.md , the command you gave gave the same result :
```
~/projects/openpaas-esn $ node ./bin/cli elasticsearch --host localhost --port 9200 --type users
debug: local/SUBSCRIBE to mongodb:connectionAvailable
[CLI] ERROR { Error: [invalid_alias_name_exception] Invalid alias name [users.idx], an index exists with the same name as the alias, with { index=real.users.idx }
    at respond (/home/arsleust/projects/openpaas-esn/node_modules/elasticsearch/src/lib/transport.js:289:15)
    at checkRespForFailure (/home/arsleust/projects/openpaas-esn/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/home/arsleust/projects/openpaas-esn/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/home/arsleust/projects/openpaas-esn/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  status: 400,
  displayName: 'BadRequest',
  message: '[invalid_alias_name_exception] Invalid alias name [users.idx], an index exists with the same name as the alias, with { index=real.users.idx }',
  path: '/real.users.idx/_alias/users.idx',
  query: {},
  body: undefined,
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"invalid_alias_name_exception","reason":"Invalid alias name [users.idx], an index exists with the same name as the alias","index":"real.users.idx"}],"type":"invalid_alias_name_exception","reason":"Invalid alias name [users.idx], an index exists with the same name as the alias","index":"real.users.idx"},"status":400}',
  toString: [Function],
  toJSON: [Function] }
```

I also tried the next command given in the same guide :
```
~/projects/openpaas-esn $ node ./bin/cli reindex --db-host localhost --db-port 27017 --db-name esn --type users
debug: local/SUBSCRIBE to mongodb:connectionAvailable
[CLI] ERROR { Error: Could not locate the bindings file. Tried:
 → /home/arsleust/projects/openpaas-esn/node_modules/ursa/build/ursaNative.node
 → /home/arsleust/projects/openpaas-esn/node_modules/ursa/build/Debug/ursaNative.node
 → /home/arsleust/projects/openpaas-esn/node_modules/ursa/build/Release/ursaNative.node
 → /home/arsleust/projects/openpaas-esn/node_modules/ursa/out/Debug/ursaNative.node
 → /home/arsleust/projects/openpaas-esn/node_modules/ursa/Debug/ursaNative.node
 → /home/arsleust/projects/openpaas-esn/node_modules/ursa/out/Release/ursaNative.node
 → /home/arsleust/projects/openpaas-esn/node_modules/ursa/Release/ursaNative.node
 → /home/arsleust/projects/openpaas-esn/node_modules/ursa/build/default/ursaNative.node
 → /home/arsleust/projects/openpaas-esn/node_modules/ursa/compiled/8.9.1/linux/x64/ursaNative.node
    at bindings (/home/arsleust/projects/openpaas-esn/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/home/arsleust/projects/openpaas-esn/node_modules/ursa/lib/ursa.js:18:37)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/arsleust/projects/openpaas-esn/backend/core/auth/jwt.js:3:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/arsleust/projects/openpaas-esn/backend/core/auth/index.js:5:8)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
  tries: 
   [ '/home/arsleust/projects/openpaas-esn/node_modules/ursa/build/ursaNative.node',
     '/home/arsleust/projects/openpaas-esn/node_modules/ursa/build/Debug/ursaNative.node',
     '/home/arsleust/projects/openpaas-esn/node_modules/ursa/build/Release/ursaNative.node',
     '/home/arsleust/projects/openpaas-esn/node_modules/ursa/out/Debug/ursaNative.node',
     '/home/arsleust/projects/openpaas-esn/node_modules/ursa/Debug/ursaNative.node',
     '/home/arsleust/projects/openpaas-esn/node_modules/ursa/out/Release/ursaNative.node',
     '/home/arsleust/projects/openpaas-esn/node_modules/ursa/Release/ursaNative.node',
     '/home/arsleust/projects/openpaas-esn/node_modules/ursa/build/default/ursaNative.node',
     '/home/arsleust/projects/openpaas-esn/node_modules/ursa/compiled/8.9.1/linux/x64/ursaNative.node' ] }
```

Seems to me that the CLI that populates MongoDB has put an user.idx index and elasticsearch fails after that...
( line `node ./bin/cli.js docker-dev --host <YOUR_DOCKER_IP> --port <PORT> --database <DBNAME>` in https://github.com/linagora/openpaas-esn/blob/master/docker/doc/install.md#2-run-the-services-with-docker-compose )

**Comment by heroandtn3** [comment]
Hello, now you can try OpenPaaS with Docker easier with docker compose, have a look here http://docs.open-paas.org/getting-started/docker/

I will close this thread, feel free to open the new one if you have any problem with our docker compose deployment.
