### ISSUE TITLE
No such user admin@open-paas.org

### ISSUE THREAD

**Issue by buzanits** [linagora/openpaas-esn#35]
I installed OpenPaaS with the Docker installation (http://docs.open-paas.org/getting-started/docker/). I cannot log in and in the console (where I started `PROVISION=true docker-compose up`) I get:

```
esn              | error: Problem while setting login failure for user admin@open-paas.org Error: No such user admin@open-paas.com
esn              |     at /var/www/backend/core/user/login.js:40:23
esn              |     at model.Query.<anonymous> (/var/www/node_modules/mongoose/lib/model.js:3403:16)
esn              |     at /var/www/node_modules/kareem/index.js:259:21
esn              |     at /var/www/node_modules/kareem/index.js:127:16
esn              |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
esn              |     at process._tickCallback (internal/process/next_tick.js:180:9)
```
Where should I start troubleshooting?

**Comment by buzanits** [comment]
Hmm, I did a new clean install and it works now. I think the problem was that the VM is was testing first crashed with out-of-memory and I just restarted it with more memory. Probably the crash ruined something. Issue closed.
