### ISSUE TITLE
OpenPaas user issue after installation

### ISSUE THREAD

**Issue by ankitjain1990** [linagora/openpaas-esn#36]
Hi Team,

I have installed OpenPaas source code on my local system(ubuntu 16.04) using the docker. I am able to login to it but after login, I am not able to access all the features of application like calendar, mail and etc.

After login when I take pointer over the username it shows me error like, " your user is currently unavailable, you can click and retry"

I am getting an error on the console.

error: Can not generate the JWT Error: No “jwt” configuration has been found
at /var/esn/openpaas-esn/backend/core/auth/jwt.js:27:23
at /var/esn/openpaas-esn/backend/core/esn-config/core.js:21:7
at _fulfilled (/var/esn/openpaas-esn/node_modules/q/q.js:854:54)
at self.promiseDispatch.done (/var/esn/openpaas-esn/node_modules/q/q.js:883:30)
at Promise.promise.promiseDispatch (/var/esn/openpaas-esn/node_modules/q/q.js:816:13)
at /var/esn/openpaas-esn/node_modules/q/q.js:624:44
at runSingle (/var/esn/openpaas-esn/node_modules/q/q.js:137:13)
at flush (/var/esn/openpaas-esn/node_modules/q/q.js:125:13)
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickCallback (internal/process/next_tick.js:180:9)

Please help me out.

**Comment by fredhampton** [comment]
Is this related to this issue

https://github.com/linagora/openpaas-esn/issues/11

**Comment by ankitjain1990** [comment]
No, I don't think so @fredhampton. I had used below URL to install the application.
https://github.com/linagora/openpaas-esn/blob/master/docker/doc/install.md
