### ISSUE TITLE
Compiling the Front End

### ISSUE THREAD

**Issue by rhclayto** [linagora/openpaas-esn#52]
Is there any way to compile the front end, a grunt command or something like that? I would like to poke around in the front end code, but am finding it kind of hard since the AngularJS view fragments seem to be in .pug format, with which I am unfamiliar.

Edit: I found pug-cli & installed it.

When trying to use pug-cli to compile the .pug templates & views, I am getting the following errors:

```bash
$ pug frontend/views

/usr/local/lib/node_modules/pug-cli/node_modules/pug-runtime/index.js:252
  throw err;
  ^

TypeError: frontend/views/commons/404.pug:15
    13|       .container-fluid
    14|         a(href="#/")
  > 15|         img(src="/images/logo.png", alt=__("OpenPaas Logo"))
    16|       div.container
    17|         div
    18|           h1 #{__('Not Found')}

__ is not a function
    at eval (eval at wrap (/usr/local/lib/node_modules/pug-cli/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:33:92)
    at template (eval at wrap (/usr/local/lib/node_modules/pug-cli/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:51:250)
    at renderFile (/usr/local/lib/node_modules/pug-cli/index.js:285:40)
    at /usr/local/lib/node_modules/pug-cli/index.js:294:7
    at Array.forEach (<anonymous>)
    at renderFile (/usr/local/lib/node_modules/pug-cli/index.js:293:8)
    at /usr/local/lib/node_modules/pug-cli/index.js:294:7
    at Array.forEach (<anonymous>)
    at renderFile (/usr/local/lib/node_modules/pug-cli/index.js:293:8)
    at /usr/local/lib/node_modules/pug-cli/index.js:149:5
```

```bash
 $ pug templates

/usr/local/lib/node_modules/pug-cli/node_modules/pug-runtime/index.js:252
  throw err;
  ^

TypeError: templates/email/digest.daily/html.pug:18
    16|               td
    17|                 div.logo
  > 18|                   a(href!=content.header.baseUrl)
    19|                     img(src="cid:logo", alt=__("OpenPaas Logo"))
    20|               td
    21|                 h2

Cannot read property 'header' of undefined
    at eval (eval at wrap (/usr/local/lib/node_modules/pug-cli/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:35:61)
    at template (eval at wrap (/usr/local/lib/node_modules/pug-cli/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:862:165)
    at renderFile (/usr/local/lib/node_modules/pug-cli/index.js:285:40)
    at /usr/local/lib/node_modules/pug-cli/index.js:294:7
    at Array.forEach (<anonymous>)
    at renderFile (/usr/local/lib/node_modules/pug-cli/index.js:293:8)
    at /usr/local/lib/node_modules/pug-cli/index.js:294:7
    at Array.forEach (<anonymous>)
    at renderFile (/usr/local/lib/node_modules/pug-cli/index.js:293:8)
    at /usr/local/lib/node_modules/pug-cli/index.js:294:7
```

**Comment by tanandy** [comment]
hi, sorry for late support. we migrated the frontend here : https://github.com/OpenPaaS-Suite/esn-frontend-inbox/

we are changing lot of things right now,

stay tune
