### ISSUE TITLE
Mongo Db issues

### ISSUE THREAD

**Issue by ricardosaracino** [linagora/openpaas-esn#67]
```
 Static hostname: ricardosaracino.com
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 02e630d90cd64421a070af054c0df790
           Boot ID: 0364b56da55245b49a5ffa45eedee861
    Virtualization: microsoft
  Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.6:GA:server
            Kernel: Linux 3.10.0-957.21.3.el7.x86_64
      Architecture: x86-64
```
``` bash
[root@openpaas ricardo]# /usr/local/bin/opctl  platformadmin init --email admin@openpaas.local
Connected to MongoDB at mongodb://localhost:27017/esn
(node:128795) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Disconnecting from MongoDB
[CLI] ERROR Error: No such user with email admin@openpaas.local
    at findUserByEmail.then.user (/usr/share/openpaas/bin/commands/platformadmin_cmds/init.js:53:27)
    at _fulfilled (/usr/share/openpaas/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/usr/share/openpaas/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/usr/share/openpaas/node_modules/q/q.js:816:13)
    at /usr/share/openpaas/node_modules/q/q.js:624:44
    at runSingle (/usr/share/openpaas/node_modules/q/q.js:137:13)
    at flush (/usr/share/openpaas/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

http://ricardosaracino.com/

**Comment by tuanlc** [comment]
Hello @ricardosaracino, 
The error log said that there is no `admin` user in the system.
Did you run the populate command which will initial required data to use OpenPaaS?

```
$ node ./bin/cli populate
```

**Comment by ricardosaracino** [comment]
It turns out I had issues running `opctl init --email admin@openpaas.local` ... solution was found in this 

https://github.com/linagora/openpaas-esn/issues/48
