### ISSUE TITLE
Docker container linagora/james-ldap-project loses connection to the OpenLDAP server regularly

### ISSUE THREAD

**Issue by alexcustos** [linagora/openpaas-esn#83]
Hello, I ran into the issue when updated OpenPaaS to version 1.5.0, but had nothing to report until I applied the latest update (v1.6.0). From a client-side, it looks like all login connections to James/OpenPaaS terminated by timeout. At the same time, everything on the server-side looked perfectly normal, no errors and even James showed some activity (rejects spam messages for example).

The latest release also started to log the followed error regarding the LDAP connection. The weird part, I have no single issue with my OpenLDAP server. I double-checked and updated it. Moreover, I added telnet to the James container and found no issue to reach the server. But there are no access attempts from James container to OpenLDAP until I restart the container. And that's the only option to get it back to operate normally. It happens randomly once in a few days.

I would appreciate any thoughts on this.

<details>
  <summary>James error</summary>

```
esn_james        | 04:24:19.968 [INFO ] o.a.j.u.r.n.LoggingRetryHandler - Retry failure. Retrying in 0 seconds
esn_james        | java.io.IOException: connection closed
esn_james        |      at com.sun.jndi.ldap.LdapClient.ensureOpen(LdapClient.java:1587)
esn_james        |      at com.sun.jndi.ldap.LdapClient.search(LdapClient.java:524)
esn_james        |      at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:1985)
esn_james        |      ... 30 common frames omitted
esn_james        | Wrapped by: javax.naming.CommunicationException: connection closed
esn_james        |      at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:2002)
esn_james        |      at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1844)
esn_james        |      at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1769)
esn_james        |      at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:392)
esn_james        |      at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:358)
esn_james        |      at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:341)
esn_james        |      at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:267)
esn_james        |      at org.apache.james.util.retry.naming.directory.RetryingDirContext$24.operation(RetryingDirContext.java:373)
esn_james        |      at org.apache.james.util.retry.ExceptionRetryHandler.perform(ExceptionRetryHandler.java:83)
esn_james        |      at org.apache.james.util.retry.naming.NamingExceptionRetryHandler.perform(NamingExceptionRetryHandler.java:55)
esn_james        |      at org.apache.james.util.retry.naming.directory.RetryingDirContext.search(RetryingDirContext.java:375)
esn_james        |      at org.apache.james.user.ldap.ReadOnlyUsersLDAPRepository.searchAndBuildUser(ReadOnlyUsersLDAPRepository.java:488)
esn_james        |      at org.apache.james.user.ldap.ReadOnlyUsersLDAPRepository.getUserByName(ReadOnlyUsersLDAPRepository.java:561)
esn_james        |      at org.apache.james.user.ldap.ReadOnlyUsersLDAPRepository.test(ReadOnlyUsersLDAPRepository.java:634)
esn_james        |      at org.apache.james.adapter.mailbox.store.UserRepositoryAuthenticator.isAuthentic(UserRepositoryAuthenticator.java:46)
esn_james        |      at org.apache.james.mailbox.store.SessionProviderImpl.isValidLogin(SessionProviderImpl.java:112)
esn_james        |      at org.apache.james.mailbox.store.SessionProviderImpl.login(SessionProviderImpl.java:60)
esn_james        |      at org.apache.james.mailbox.store.StoreMailboxManager.login(StoreMailboxManager.java:236)
esn_james        |      at org.apache.james.imap.processor.AbstractAuthProcessor.doAuth(AbstractAuthProcessor.java:70)
esn_james        |      at org.apache.james.imap.processor.AuthenticateProcessor.doPlainAuth(AuthenticateProcessor.java:97)
esn_james        |      at org.apache.james.imap.processor.AuthenticateProcessor.lambda$processRequest$0(AuthenticateProcessor.java:76)
esn_james        |      at org.apache.james.imapserver.netty.ImapLineHandlerAdapter.messageReceived(ImapLineHandlerAdapter.java:54)
esn_james        |      at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
esn_james        |      at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
esn_james        |      at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
esn_james        |      at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
esn_james        |      at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
esn_james        |      at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
esn_james        |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
esn_james        |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
esn_james        |      at java.lang.Thread.run(Thread.java:748)
esn_james        | 04:24:19.968 [INFO ] o.a.j.u.r.n.LoggingRetryHandler - Retry failure. Retrying in 1 seconds
...
```
</details>

**Comment by alexcustos** [comment]
I'm closing the ticket. It was nothing about James. The issue was caused by the osixia/phpldapadmin container. That thing didn't close connections properly. Everything back to normal when I pulled the latest version 0.9.0.
