### ISSUE TITLE
Elasticsearch error while trying to search emails in OpenPaaS UI: [nested] nested object under path [headers] is not of nested type

### ISSUE THREAD

**Issue by alexcustos** [linagora/openpaas-esn#94]
<details>
  <summary>Here's the logged error</summary>

```
esn_james        | 06:32:08.564 [ERROR] o.a.j.j.h.JMAPApiRoutes - Internal server error
esn_james        | org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
esn_james        | 	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)
esn_james        | 	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1406)
esn_james        | 	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1382)
esn_james        | 	at org.elasticsearch.client.RestHighLevelClient$1.onFailure(RestHighLevelClient.java:1357)
esn_james        | 	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:844)
esn_james        | 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:548)
esn_james        | 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:529)
esn_james        | 	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
esn_james        | 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
esn_james        | 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
esn_james        | 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
esn_james        | 	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
esn_james        | 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
esn_james        | 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
esn_james        | 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
esn_james        | 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
esn_james        | 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
esn_james        | 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
esn_james        | 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
esn_james        | 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
esn_james        | 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
esn_james        | 	at java.base/java.lang.Thread.run(Unknown Source)
esn_james        | 	Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://elasticsearch:9200], URI [/mailboxReadAlias/_doc/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&scroll=1m&search_type=query_then_fetch&batched_reduce_size=512], status line [HTTP/1.1 400 Bad Request]
esn_james        | {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: {
  "bool" : {
    "must" : [
      {
        "bool" : {
          "should" : [
            {
              "nested" : {
                "query" : {
                  "bool" : {
                    "should" : [
                      {
                        "match" : {
                          "from.name" : {
                            "query" : "report",
                            "operator" : "OR",
                            "prefix_length" : 0,
                            "max_expansions" : 50,
                            "fuzzy_transpositions" : true,
                            "lenient" : false,
                            "zero_terms_query" : "NONE",
                            "auto_generate_synonyms_phrase_query" : true,
                            "boost" : 1.0
                          }
                        }
                      },
                      {
                        "match" : {
                          "from.address" : {
                            "query" : "report",
                            "operator" : "OR",
                            "prefix_length" : 0,
                            "max_expansions" : 50,
                            "fuzzy_transpositions" : true,
                            "lenient" : false,
                            "zero_terms_query" : "NONE",
                            "auto_generate_synonyms_phrase_query" : true,
                            "boost" : 1.0
                          }
                        }
                      },
                      {
                        "match" : {
                          "from.address.raw" : {
                            "query" : "report",
                            "operator" : "OR",
                            "prefix_length" : 0,
                            "max_expansions" : 50,
                            "fuzzy_transpositions" : true,
                            "lenient" : false,
                            "zero_terms_query" : "NONE",
                            "auto_generate_synonyms_phrase_query" : true,
                            "boost" : 1.0
                          }
                        }
                      }
                    ],
                    "adjust_pure_negative" : true,
                    "boost" : 1.0
                  }
                },
                "path" : "from",
                "ignore_unmapped" : false,
                "score_mode" : "avg",
                "boost" : 1.0
              }
            },
            {
              "nested" : {
                "query" : {
                  "bool" : {
                    "should" : [
                      {
                        "match" : {
                          "to.name" : {
                            "query" : "report",
                            "operator" : "OR",
                            "prefix_length" : 0,
                            "max_expansions" : 50,
                            "fuzzy_transpositions" : true,
                            "lenient" : false,
                            "zero_terms_query" : "NONE",
                            "auto_generate_synonyms_phrase_query" : true,
                            "boost" : 1.0
                          }
                        }
                      },
                      {
                        "match" : {
                          "to.address" : {
                            "query" : "report",
                            "operator" : "OR",
                            "prefix_length" : 0,
                            "max_expansions" : 50,
                            "fuzzy_transpositions" : true,
                            "lenient" : false,
                            "zero_terms_query" : "NONE",
                            "auto_generate_synonyms_phrase_query" : true,
                            "boost" : 1.0
                          }
                        }
                      },
                      {
                        "match" : {
                          "to.address.raw" : {
                            "query" : "report",
                            "operator" : "OR",
                            "prefix_length" : 0,
                            "max_expansions" : 50,
                            "fuzzy_transpositions" : true,
                            "lenient" : false,
                            "zero_terms_query" : "NONE",
                            "auto_generate_synonyms_phrase_query" : true,
                            "boost" : 1.0
                          }
                        }
                      }
                    ],
                    "adjust_pure_negative" : true,
                    "boost" : 1.0
                  }
                },
                "path" : "to",
                "ignore_unmapped" : false,
                "score_mode" : "avg",
                "boost" : 1.0
              }
            },
            {
              "nested" : {
                "query" : {
                  "bool" : {
                    "should" : [
                      {
                        "match" : {
                          "cc.name" : {
                            "query" : "report",
                            "operator" : "OR",
                            "prefix_length" : 0,
                            "max_expansions" : 50,
                            "fuzzy_transpositions" : true,
                            "lenient" : false,
                            "zero_terms_query" : "NONE",
                            "auto_generate_synonyms_phrase_query" : true,
                            "boost" : 1.0
                          }
                        }
                      },
                      {
                        "match" : {
                          "cc.address" : {
                            "query" : "report",
                            "operator" : "OR",
                            "prefix_length" : 0,
                            "max_expansions" : 50,
                            "fuzzy_transpositions" : true,
                            "lenient" : false,
                            "zero_terms_query" : "NONE",
                            "auto_generate_synonyms_phrase_query" : true,
                            "boost" : 1.0
                          }
                        }
                      },
                      {
                        "match" : {
                          "cc.address.raw" : {
                            "query" : "report",
                            "operator" : "OR",
                            "prefix_length" : 0,
                            "max_expansions" : 50,
                            "fuzzy_transpositions" : true,
                            "lenient" : false,
                            "zero_terms_query" : "NONE",
                            "auto_generate_synonyms_phrase_query" : true,
                            "boost" : 1.0
                          }
                        }
                      }
                    ],
                    "adjust_pure_negative" : true,
                    "boost" : 1.0
                  }
                },
                "path" : "cc",
                "ignore_unmapped" : false,
                "score_mode" : "avg",
                "boost" : 1.0
              }
            },
            {
              "nested" : {
                "query" : {
                  "bool" : {
                    "should" : [
                      {
                        "match" : {
                          "bcc.name" : {
                            "query" : "report",
                            "operator" : "OR",
                            "prefix_length" : 0,
                            "max_expansions" : 50,
                            "fuzzy_transpositions" : true,
                            "lenient" : false,
                            "zero_terms_query" : "NONE",
                            "auto_generate_synonyms_phrase_query" : true,
                            "boost" : 1.0
                          }
                        }
                      },
                      {
                        "match" : {
                          "bcc.address" : {
                            "query" : "report",
                            "operator" : "OR",
                            "prefix_length" : 0,
                            "max_expansions" : 50,
                            "fuzzy_transpositions" : true,
                            "lenient" : false,
                            "zero_terms_query" : "NONE",
                            "auto_generate_synonyms_phrase_query" : true,
                            "boost" : 1.0
                          }
                        }
                      },
                      {
                        "match" : {
                          "bcc.address.raw" : {
                            "query" : "report",
                            "operator" : "OR",
                            "prefix_length" : 0,
                            "max_expansions" : 50,
                            "fuzzy_transpositions" : true,
                            "lenient" : false,
                            "zero_terms_query" : "NONE",
                            "auto_generate_synonyms_phrase_query" : true,
                            "boost" : 1.0
                          }
                        }
                      }
                    ],
                    "adjust_pure_negative" : true,
                    "boost" : 1.0
                  }
                },
                "path" : "bcc",
                "ignore_unmapped" : false,
                "score_mode" : "avg",
                "boost" : 1.0
              }
            },
            {
              "nested" : {
                "query" : {
                  "bool" : {
                    "must" : [
                      {
                        "term" : {
                          "headers.name" : {
                            "value" : "subject",
                            "boost" : 1.0
                          }
                        }
                      },
                      {
                        "match" : {
                          "headers.value" : {
                            "query" : "report",
                            "operator" : "OR",
                            "prefix_length" : 0,
                            "max_expansions" : 50,
                            "fuzzy_transpositions" : true,
                            "lenient" : false,
                            "zero_terms_query" : "NONE",
                            "auto_generate_synonyms_phrase_query" : true,
                            "boost" : 1.0
                          }
                        }
                      }
                    ],
                    "adjust_pure_negative" : true,
                    "boost" : 1.0
                  }
                },
                "path" : "headers",
                "ignore_unmapped" : false,
                "score_mode" : "avg",
                "boost" : 1.0
              }
            },
            {
              "bool" : {
                "should" : [
                  {
                    "match" : {
                      "attachments.textContent" : {
                        "query" : "report",
                        "operator" : "OR",
                        "prefix_length" : 0,
                        "max_expansions" : 50,
                        "fuzzy_transpositions" : true,
                        "lenient" : false,
                        "zero_terms_query" : "NONE",
                        "auto_generate_synonyms_phrase_query" : true,
                        "boost" : 1.0
                      }
                    }
                  }
                ],
                "adjust_pure_negative" : true,
                "boost" : 1.0
              }
            },
            {
              "bool" : {
                "should" : [
                  {
                    "match" : {
                      "textBody" : {
                        "query" : "report",
                        "operator" : "OR",
                        "prefix_length" : 0,
                        "max_expansions" : 50,
                        "fuzzy_transpositions" : true,
                        "lenient" : false,
                        "zero_terms_query" : "NONE",
                        "auto_generate_synonyms_phrase_query" : true,
                        "boost" : 1.0
                      }
                    }
                  },
                  {
                    "match" : {
                      "textBody.splitEmail" : {
                        "query" : "report",
                        "operator" : "OR",
                        "prefix_length" : 0,
                        "max_expansions" : 50,
                        "fuzzy_transpositions" : true,
                        "lenient" : false,
                        "zero_terms_query" : "NONE",
                        "auto_generate_synonyms_phrase_query" : true,
                        "boost" : 1.0
                      }
                    }
                  },
                  {
                    "match" : {
                      "htmlBody.splitEmail" : {
                        "query" : "report",
                        "operator" : "OR",
                        "prefix_length" : 0,
                        "max_expansions" : 50,
                        "fuzzy_transpositions" : true,
                        "lenient" : false,
                        "zero_terms_query" : "NONE",
                        "auto_generate_synonyms_phrase_query" : true,
                        "boost" : 1.0
                      }
                    }
                  },
                  {
                    "match" : {
                      "htmlBody" : {
                        "query" : "report",
                        "operator" : "OR",
                        "prefix_length" : 0,
                        "max_expansions" : 50,
                        "fuzzy_transpositions" : true,
                        "lenient" : false,
                        "zero_terms_query" : "NONE",
                        "auto_generate_synonyms_phrase_query" : true,
                        "boost" : 1.0
                      }
                    }
                  }
                ],
                "adjust_pure_negative" : true,
                "boost" : 1.0
              }
            },
            {
              "bool" : {
                "should" : [
                  {
                    "term" : {
                      "attachments.fileName" : {
                        "value" : "report",
                        "boost" : 1.0
                      }
                    }
                  }
                ],
                "adjust_pure_negative" : true,
                "boost" : 1.0
              }
            }
          ],
          "adjust_pure_negative" : true,
          "boost" : 1.0
        }
      }
    ],
    "filter" : [
      {
        "terms" : {
          "mailboxId" : [
            "02963400-2235-11e9-96b6-9b463fe2e7be",
            "029103e0-2235-11e9-96b6-9b463fe2e7be",
            "3fb22a50-2236-11e9-96b6-9b463fe2e7be",
            "02921550-2235-11e9-96b6-9b463fe2e7be",
            "3fb6be30-2236-11e9-96b6-9b463fe2e7be",
            "02976c80-2235-11e9-96b6-9b463fe2e7be",
            "0293c300-2235-11e9-96b6-9b463fe2e7be",
            "029549a0-2235-11e9-96b6-9b463fe2e7be"
          ],
          "boost" : 1.0
        }
      }
    ],
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}","index_uuid":"c0MMLrWGTja_A0P984M04Q","index":"mailbox_v1"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"mailbox_v1","node":"YeGBJd_5RHmJvOWg7mvnwQ","reason":{"type":"query_shard_exception","reason":"failed to create query: {

    ... [ EXACTLY THE SAME QUERY AS ABOVE ] ...

}","index_uuid":"c0MMLrWGTja_A0P984M04Q","index":"mailbox_v1","caused_by":{"type":"illegal_state_exception","reason":"[nested] nested object under path [headers] is not of nested type"}}}]},"status":400}
esn_james        | 		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:540)
esn_james        | 		... 16 common frames omitted
```
</details>

The first time I received this error after updated OpenPaaS to version 1.8.0. Recently I tried to debug the issue, but I didn't find any solution.

Now I'm running v1.8.1-rc8 with recommended software versions (https://github.com/linagora/openpaas-esn/blob/1.8.1-rc8/docker/dockerfiles/docker-compose-commons.yml) except James. It's `james-ldap-project:openpaas-1.7.16-rc1` container (I also tried `branch-master`).

The log file doesn't provide enough information to execute the problem query, and trying to rebuild the `mailbox_v1` index as I did before (https://github.com/linagora/openpaas-esn/issues/61) renders it completely broken.

Everything else seems working perfectly fine.

Did I miss something while updating?

**Comment by alexcustos** [comment]
It seems the problem was resolved. I re-provisioned the instance to new volumes, replaced Elasticsearch volume with a fresh copy, and executed the ReindexAll command on the James side. It seems there's no downside to this solution. So the issue can be closed.

**Comment by chibenwa** [comment]
> The first time I received this error after updated OpenPaaS to version 1.8.0.

Is it related to https://github.com/linagora/james-project/blob/master/upgrade-instructions.md#elasticsearch-performance-enhancements ?

Yes you likely applied the right procedure (Kudo!)

For the explanation, the code was expected a nested header structure while your data still followed the old one.

Cheers,

Benoit
